from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .views import (carta_intencao_views, conjuge_familia_views,
                    dados_adicionais_views, dados_bancarios_views,
                    dados_candidato_views, email_redes_sociais_views,
                    emprego_views, enderecos_views, ensino_views,
                    enviar_formulario_views, experiencia_seguranca_views,
                    familiares_views, habilitacao_motorista_views,
                    hobbies_clube_views, informacao_candidato_views,
                    inquerito_views, parente_policial_amigos_views,
                    patrimonio_veiculo_views, protestos_dividas_views,
                    servico_militar_views)

app_name = "formulario"

urlpatterns = [
    path(
        "formulario_dados_adicionais/",
        dados_adicionais_views.formulario_dados_adicionais,
        name="formulario_dados_adicionais",
    ),
    path(
        "formulario_dados_adicionais/enviado/",
        dados_adicionais_views.formulario_dados_adicionais_enviado,
        name="formulario_dados_adicionais_enviado",
    ),
    path("get_cidades/", dados_adicionais_views.get_cidades, name="get_cidades"),
    path(
        "formulario_email_redes_sociais/",
        email_redes_sociais_views.formulario_email_redes_sociais,
        name="formulario_email_redes_sociais",
    ),
    path(
        "formulario_email_redes_sociais/enviado/",
        email_redes_sociais_views.formulario_email_redes_sociais_enviado,
        name="formulario_email_redes_sociais_enviado",
    ),
    path(
        "formulario_dados_bancarios/",
        dados_bancarios_views.dados_bancarios,
        name="formulario_dados_bancarios",
    ),
    path(
        "formulario_dados_bancarios/enviado/",
        dados_bancarios_views.dados_bancarios_enviado,
        name="formulario_dados_bancarios_enviado",
    ),
    path(
        "formulario_informacao_candidato/",
        informacao_candidato_views.informacao_candidato,
        name="formulario_informacao_candidato",
    ),
    path(
        "formulario_informacao_candidato/enviado/",
        informacao_candidato_views.informacao_candidato_enviado,
        name="formulario_informacao_candidato_enviado",
    ),
    path("lista/", dados_candidato_views.lista, name="inlineform_lista"),
    path(
        "formulario_dados_candidato/<int:candidato_id>/",
        dados_candidato_views.dados_candidato,
        name="formulario_dados_candidato",
    ),
    path(
        "formulario_dados_candidato_enviado/<int:candidato_id>/",
        dados_candidato_views.dados_candidato_eviado,
        name="formulario_dados_candidato_enviado",
    ),
    path(
        "formulario_familiares/<int:candidato_id>/",
        familiares_views.familiares,
        name="formulario_familiares",
    ),
    path(
        "formulario_familiares_enviado/<int:candidato_id>/",
        familiares_views.familiares_enviado,
        name="formulario_familiares_enviado",
    ),
    path(
        "formulario_conjuge_familia/",
        conjuge_familia_views.conjuge_familia,
        name="formulario_conjuge_familia",
    ),
    path(
        "formulario_conjuge_familia/enviado/",
        conjuge_familia_views.conjuge_familia_enviado,
        name="formulario_conjuge_familia_enviado",
    ),
    path(
        "formulario_parente_policial_amigos/<int:candidato_id>/",
        parente_policial_amigos_views.parente_policial_amigos,
        name="formulario_parente_policial_amigos",
    ),
    path(
        "formulario_parente_policial_amigos/enviado/<int:candidato_id>/",
        parente_policial_amigos_views.parente_policial_amigos_enviado,
        name="formulario_parente_policial_amigos_enviado",
    ),
    path(
        "formulario_hobbies_clube/<int:candidato_id>/",
        hobbies_clube_views.hobbies_clube,
        name="formulario_hobbies_clube",
    ),
    path(
        "formulario_hobbies_clube/enviado/<int:candidato_id>/",
        hobbies_clube_views.hobbies_clube_enviado,
        name="formulario_hobbies_clube_enviado",
    ),
    path(
        "formulario_inquerito/<int:candidato_id>/",
        inquerito_views.inquerito,
        name="formulario_inquerito",
    ),
    path(
        "formulario_inquerito/enviado/<int:candidato_id>/",
        inquerito_views.inquerito_enviado,
        name="formulario_inquerito_enviado",
    ),
    path(
        "formulario_emprego/<int:candidato_id>/",
        emprego_views.emprego,
        name="formulario_emprego",
    ),
    path(
        "formulario_emprego/enviado/<int:candidato_id>/",
        emprego_views.emprego_enviado,
        name="formulario_emprego_enviado",
    ),
    path(
        "formulario_experiencia_seguranca/<int:candidato_id>/",
        experiencia_seguranca_views.experiencia_seguranca,
        name="formulario_experiencia_seguranca",
    ),
    path(
        "formulario_experiencia_seguranca/enviado/<int:candidato_id>/",
        experiencia_seguranca_views.experiencia_seguranca_enviado,
        name="formulario_experiencia_seguranca_enviado",
    ),
    path(
        "formulario_servico_militar/<int:candidato_id>/",
        servico_militar_views.servico_militar,
        name="formulario_servico_militar",
    ),
    path(
        "formulario_servico_militar/enviado/<int:candidato_id>/",
        servico_militar_views.servico_militar_enviado,
        name="formulario_servico_militar_enviado",
    ),
    path(
        "formulario_enderecos/<int:candidato_id>/",
        enderecos_views.enderecos,
        name="formulario_enderecos",
    ),
    path(
        "formulario_enderecos/enviado/<int:candidato_id>/",
        enderecos_views.enderecos_enviado,
        name="formulario_enderecos_enviado",
    ),
    path(
        "formulario_ensino/<int:candidato_id>/",
        ensino_views.ensino,
        name="formulario_ensino",
    ),
    path(
        "formulario_ensino/enviado/<int:candidato_id>/",
        ensino_views.ensino_enviado,
        name="formulario_ensino_enviado",
    ),
    path(
        "formulario_habilitacao_motorista/<int:candidato_id>/",
        habilitacao_motorista_views.habilitacao_motorista,
        name="formulario_habilitacao_motorista",
    ),
    path(
        "formulario_habilitacao_motorista/enviado/<int:candidato_id>/",
        habilitacao_motorista_views.habilitacao_motorista_enviado,
        name="formulario_habilitacao_motorista_enviado",
    ),
    path(
        "formulario_protestos_dividas/<int:candidato_id>/",
        protestos_dividas_views.protestos_dividas,
        name="formulario_protestos_dividas",
    ),
    path(
        "formulario_protestos_dividas/enviado/<int:candidato_id>/",
        protestos_dividas_views.protestos_dividas_enviado,
        name="formulario_protestos_dividas_enviado",
    ),
    path(
        "formulario_patrimonio_veiculo/<int:candidato_id>/",
        patrimonio_veiculo_views.patrimonio_veiculo,
        name="formulario_patrimonio_veiculo",
    ),
    path(
        "formulario_patrimonio_veiculo/enviado/<int:candidato_id>/",
        patrimonio_veiculo_views.patrimonio_veiculo_enviado,
        name="formulario_patrimonio_veiculo_enviado",
    ),
    path(
        "formulario_carta_intencao/<int:candidato_id>/",
        carta_intencao_views.carta_intencao,
        name="formulario_carta_intencao",
    ),
    path(
        "formulario_carta_intencao/enviado/<int:candidato_id>/",
        carta_intencao_views.carta_intencao_enviado,
        name="formulario_carta_intencao_enviado",
    ),
    path(
        "formulario_enviado/<int:candidato_id>/",
        enviar_formulario_views.enviar_formulario,
        name="formulario_enviado",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
