# Generated by Django 4.2.3 on 2023-07-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatriculaCpf',
            fields=[
                ('id_matricula_cpf', models.AutoField(primary_key=True, serialize=False)),
                ('num_matricula', models.IntegerField(max_length=30)),
                ('cpf', models.IntegerField(max_length=11)),
            ],
        ),
    ]
