# Generated by Django 4.2.3 on 2023-07-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculacpf',
            name='cpf',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='matriculacpf',
            name='num_matricula',
            field=models.IntegerField(),
        ),
    ]
