# Generated by Django 4.2.3 on 2023-07-27 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_matriculacpf_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculacpf',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='matriculacpf',
            name='num_matricula',
            field=models.CharField(max_length=50),
        ),
    ]
