# Generated by Django 4.2.3 on 2023-07-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_matriculacpf_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriculacpf',
            name='cadastrado',
            field=models.BooleanField(default=False),
        ),
    ]
