# Generated by Django 4.2.3 on 2023-09-14 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_rename_id_matricula_cpf_matriculacpf_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matriculacpf',
            options={'verbose_name': 'Matrícula e CPF', 'verbose_name_plural': 'Matrículas e CPFs'},
        ),
    ]
