# Generated by Django 4.2.3 on 2024-02-22 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_matriculacpf_cadastrado_alter_matriculacpf_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculacpf',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
