# Generated by Django 4.2.3 on 2023-08-24 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formulario', '0002_alter_dadoscandidato_nome_candidato'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadoscandidato',
            name='apelido_candidato',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='dadoscandidato',
            name='estado_civil',
            field=models.CharField(choices=[('Solteiro', 'Solteiro'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Viúvo', 'Viúvo')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dadoscandidato',
            name='idiomas',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dadoscandidato',
            name='nacionalidade',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='dadoscandidato',
            name='natural',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='dadoscandidato',
            name='nome_mae',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dadoscandidato',
            name='nome_pai',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dadoscandidato',
            name='num_carteira_profissional',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='dadoscandidato',
            name='num_identidade',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dadoscandidato',
            name='num_titulo_eleitor',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dadoscandidato',
            name='orgao_emissor',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dadoscandidato',
            name='serie_carteira_prof',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='dadoscandidato',
            name='uf_natural',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dadoscandidato',
            name='zona_titulo',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='DadosCandidato2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_candidato', models.CharField(max_length=100, null=True)),
                ('data_nasc_candidato', models.DateField()),
                ('apelido_candidato', models.CharField(max_length=60)),
                ('nacionalidade', models.CharField(max_length=60)),
                ('natural', models.CharField(max_length=60)),
                ('uf_natural', models.CharField(max_length=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
