# Generated by Django 4.2.3 on 2023-08-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0005_remove_dadoscandidato_data_nasc_candidato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadoscandidato',
            name='data_nasc_candidato',
            field=models.DateField(null=True),
        ),
    ]
